-- ==========================
-- REMOVER TABELAS (ORACLE)
-- ==========================
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE alugueis CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE livros CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE usuarios CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- ==========================
-- USUÁRIOS
-- ==========================
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf VARCHAR2(11) NOT NULL UNIQUE,
    email VARCHAR2(255) NOT NULL UNIQUE,
    senha VARCHAR2(255) NOT NULL,
    tipo VARCHAR2(10) NOT NULL
        CHECK (tipo IN ('aluno', 'admin'))
);

-- ==========================
-- LIVROS
-- ==========================
CREATE TABLE livros (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    autor VARCHAR2(255) NOT NULL,
    ano_publicacao NUMBER(4) NOT NULL,
    descricao CLOB NOT NULL,
    imagem VARCHAR2(255) NOT NULL,
    disponivel NUMBER(1) DEFAULT 1
        CHECK (disponivel IN (0,1))
);

-- ==========================
-- ALUGUÉIS
-- ==========================
CREATE TABLE alugueis (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_livro NUMBER NOT NULL,
    id_usuario NUMBER NOT NULL,
    data_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_devolucao DATE,
    status VARCHAR2(15) DEFAULT 'alugado'
        CHECK (status IN ('alugado', 'devolvido')),

    CONSTRAINT fk_livro
        FOREIGN KEY (id_livro)
        REFERENCES livros(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id)
        ON DELETE CASCADE
);
